CREATE TABLE weather_info (
    cloud INTEGER,
    feelslike_c FLOAT,
    feelslike_f FLOAT,
    gust_kph FLOAT,
    gust_mph FLOAT,
    humidity FLOAT,
    is_day BOOLEAN,
    last_updated TIMESTAMP,
    last_updated_epoch INTEGER,
    precip_in FLOAT,
    precip_mm FLOAT,
    pressure_in FLOAT,
    pressure_mb FLOAT,
    temp_c FLOAT,
    temp_f FLOAT,
    uv FLOAT,
    vis_km FLOAT,
    vis_miles FLOAT,
    wind_degree INTEGER,
    wind_dir VARCHAR(10),
    wind_kph FLOAT,
    wind_mph FLOAT,
    country VARCHAR(30),
    lat FLOAT,
    "localtime" TIMESTAMP,
    localtime_epoch INTEGER,
    lon FLOAT,
    name VARCHAR(30),
    "region" VARCHAR(30),
    tz_id VARCHAR(100)
);

DROP TABLE weather_info;